# Generated by Django 5.0 on 2023-12-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('photo_of_out_view', models.ImageField(upload_to='house_photos')),
                ('photo_of_salon_view', models.ImageField(upload_to='house_photos')),
                ('photo_of_baedroom_view', models.ImageField(upload_to='house_photos')),
                ('photo_of_bathroom_view', models.ImageField(upload_to='house_photos')),
                ('photo_of_kichn_view', models.ImageField(upload_to='house_photos')),
                ('baderoom', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=1000000)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('limited', 'Limited'), ('pending', 'Pending')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('square_footage', models.IntegerField()),
                ('city', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('year_built', models.IntegerField()),
            ],
        ),
    ]
